# Generated by Django 5.2.10 on 2026-01-26 13:43

import django.core.validators
import django.db.models.deletion
import expenses.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01, message='Amount must be positive')])),
                ('date', models.DateTimeField(auto_now_add=True, validators=[expenses.validators.validate_dat_not_future])),
                ('notes', models.TextField(blank=True, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expenses', to='categories.category')),
                ('projects', models.ManyToManyField(blank=True, related_name='expenses', to='projects.project')),
            ],
        ),
    ]
